# Generated by Django 5.0.7 on 2024-08-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('guardian_name', models.CharField(max_length=50)),
            ],
        ),
    ]
