# Generated by Django 5.0.7 on 2024-08-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinform',
            name='date_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
