# Generated by Django 5.0.7 on 2024-08-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_joinform_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, upload_to='gallery/')),
                ('player_name', models.CharField(max_length=70)),
                ('caption', models.TextField()),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
