# Generated by Django 5.0.7 on 2024-08-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sportgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportgallery',
            name='player_name',
        ),
    ]
