# Generated by Django 5.0.7 on 2024-08-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_sportgallery_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportgallery',
            name='caption',
        ),
    ]
