# Generated by Django 5.0.7 on 2024-08-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_sportgallery_caption_alter_sportgallery_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportgallery',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='gallery/'),
        ),
    ]
