# Generated by Django 5.0.7 on 2024-08-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_sportgallery_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team_logo', models.ImageField(upload_to='team_img/')),
                ('head_coach', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sportgallery')),
            ],
        ),
    ]
