# Generated by Django 5.0.7 on 2024-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(default=None, upload_to='team_img/'),
        ),
    ]
