# Generated by Django 5.0.7 on 2024-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_team_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='team_img/'),
        ),
    ]
