# Generated by Django 5.0.7 on 2024-08-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_fixtures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixtures',
            name='team_logo',
        ),
        migrations.AddField(
            model_name='fixtures',
            name='team1_logo',
            field=models.ImageField(default='media/images (6).jpeg', upload_to='team1_logo/'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='team1_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='team2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team2_logo/'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='team2_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
