# Generated by Django 5.0.7 on 2024-08-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_fixtures_team_logo_fixtures_team1_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
        migrations.AddField(
            model_name='team',
            name='player',
            field=models.ManyToManyField(to='base.sportgallery'),
        ),
    ]
