# Generated by Django 5.0.7 on 2024-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_news_id_news_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='post_id',
        ),
        migrations.AddField(
            model_name='news',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
